source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'ZhiHuDaily' do
    pod 'Alamofire'
    pod 'YYText'
    pod 'SnapKit'
    pod 'SwiftyJSON'
    pod 'SwiftDate'
    pod 'YYWebImage'
    pod 'MJRefresh'
    pod 'Toast-Swift'
    pod 'MMDrawerController'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
